accounts/urls.py
# from allauth.account.views import LoginView
from django.contrib.auth.views import LoginView


from django.conf.urls import url
from django.urls import path
from . import views
from django.conf import settings
from django.contrib.auth import views as auth_views
from .Forms import LoginForm

app_name ='accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    # path('login/', views.login, name='login'),
    path('login/', views.main_login, name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page="main:main"), name='logout'),
    path('mypage', views.mypage, name='user_profile'),
    path('mypage/edit', views.edit_mypage, name='edit_mypage')
]

jobssul/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.shortcuts import render
from django.urls import path, include


urlpatterns = [
    path('main/', include('main.urls', namespace='main')),
    path('admin/', admin.site.urls),

    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('mypage/', include('accounts.urls', namespace='mypage')),
    path('notice/', include('notice.urls', namespace='notice')),
    path('claim/', include('claim.urls', namespace='claim')),
    path('accounts/', include('allauth.urls'))
]

main/urls.py
from django.urls import path, re_path
from . import views
from main.views import main_detail, main_create

app_name='main'

urlpatterns = [
    path('', views.main_page, name='main'),
    path('post/', views.main_post, name='post'),
    path('post/<int:post_pk>/', views.main_detail, name='detail'),
    path('create/', views.main_create, name='create'),
    path('post/<int:post_pk>/edit/', views.main_edit, name='edit'),
    path('post/<int:post_pk>/delete/', views.main_delete , name='delete'),
    path('post/<int:post_pk>/comment/new/', views.comment_new, name='comment_new'),
    path('post/<int:pk>/comment/edit/', views.comment_edit, name='comment_edit'),
    path('post/<int:pk>/comment/delete/', views.comment_delete, name='comment_delete'),
    path('like/', views.like_post, name='like_post'),
    path('best/', views.best_post, name='best_post'),
    # path('post/<int:pk>/comment/like_comment/', views.like_comment, name='like_comment'),
    path('like_comment/', views.like_comment, name='like_comment'),
    path('post/<int:post_pk>/scrap_post/', views.scrap_post, name='scrap_post'),
    path('category/', views.category, name='category')
]

accounts/models.py
from django.db import models
from builtins import property, ValueError
from django.db import models
from django.contrib.auth.models import BaseUserManager, AbstractBaseUser, PermissionsMixin
from django.core.mail import send_mail
from django.utils.translation import ugettext_lazy as _


#유저생성관리자
class UserManager(BaseUserManager):
    def create_user(self, username, nickname, email, password=None):
        if not email:
            raise ValueError(_('Users must have an email address'))

        user = self.model(
            email=self.normalize_email(email),
            nickname=nickname,
            username=username,
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, username, nickname, email, password):
        user = self.create_user(
            email=email,
            password=password,
            nickname=nickname,
            username = username,
        )

        user.is_superuser= True

        if user.is_superuser is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        user.save(using=self._db)
        return user


#유저모델
class User(AbstractBaseUser, PermissionsMixin):
    username = models.CharField(max_length=30, verbose_name='이름')
    nickname = models.CharField(max_length=10, unique=True, verbose_name='닉네임')
    email = models.EmailField(max_length=255, unique=True, verbose_name='이메일')
    reside = models.TextField(max_length=50, verbose_name='거주지', blank=True, null=True)
    date_joined = models.DateTimeField(auto_now_add=True)

    is_admin = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)

    objects = UserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username', 'nickname',]

    class Meta:
        ordering = ('-date_joined',)

    def __str__(self):
        return self.username + "(nickname:{})".format(self.nickname)

    def get_full_name(self):
        return self.nickname

    def get_short_name(self):
        return self.nickname

    @property
    def is_staff(self):
        return self.is_superuser

    # def email_user(self, subject, message, from_email=None):
    #     send_mail(subject, message, from_email, [self.email])

accounts/views.py
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import login, authenticate
from django.http import HttpResponse, JsonResponse, HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404


from .models import *
from django.views.generic import TemplateView
from django.shortcuts import render, redirect
from django.urls import reverse
from .Forms import UserCreationForm, LoginForm, UpdateProfile
from main.models import Post, Comment
from main.views import scrap_post
from django.contrib.auth import login as auth_login


def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            return redirect(settings.LOGIN_URL)
        else:
            messages.error(request, '정보를 정확히 입력해주세요.')
            return render(request, 'accounts/signup_form.html', {
                'form': form
            })
    else:
        form = UserCreationForm()
        return render(request, 'accounts/signup_form.html', {
                'form': form,
    })


#로그인
def main_login(request):
    if request.method == "POST":
        form = LoginForm()
        email = request.POST['email']
        password = request.POST['password']
        user = authenticate(request, username=email, password=password)

        if user is not None:
            auth_login(request, user)
            return redirect('main:main')
        else:
            messages.error(request, '로그인 실패. 다시 시도 해보세요.')
            return redirect('accounts:login')
    else:
        form = LoginForm()
        return render(request, 'accounts/login_form.html',{
            'form': form
        })

      
@login_required
def mypage(request):
    if request.method =='GET':
        user = request.user
        user_posts = Post.objects.filter(author=user)
        scrap_posts=user.scrap.all()
        user_comments = Comment.objects.filter(author=user)
        data = {
            'profile_user': user,
            'my_posts': user_posts,
            'my_comments': user_comments,
            'scrap_posts':scrap_posts,
        }
        return render(request, 'accounts/about.html', data)

@login_required
def edit_mypage(request):
    args={}
    if request.method=='POST':
        form=UpdateProfile(request.POST, instance=request.user)
        form.actual_user=request.user
        if form.is_valid():
            form.save()
            return redirect('accounts:user_profile')
    else:
        form = UpdateProfile()

    args['form']=form
    return render(request, 'accounts/edit_mypage.html', args)

accounts/templates/accounts/about.html
{% extends "header.html" %}
{% load static %}

{% block below_nav %}
        <title>프로필</title>
        <link rel="stylesheet" type="text/css" href="{% static 'accounts/about.css' %}">

    <style>
        #profile {
            background-color: #daf1de;
            padding: 10px;
            margin-left: 20px;
            margin-right: 20px;
        }

    </style>
    <body>
        {% if user.is_authenticated %}
        <div id="profile">
            <div>
                <div class="button_container" style=" display: block; margin-bottom: 20px"><h3>프로필 페이지</h3><a href="{% url 'accounts:edit_mypage' %}" class="btn btn-warning btn btn-primary btn-lg">내정보 수정</a>
            <div>
                <table class="type01">
                    <tr>
                        <th>이름</th>
                        <td>{{ user.username }}</td>
                    </tr>
                    <tr>
                        <th>닉네임</th>
                        <td>{{ user.nickname }}</td>
                    </tr>
                    <tr>
                        <th>주소</th>
                        <td>{{ user.reside }}</td>
                    </tr>
                    <tr>
                        <th>이메일</th>
                        <td>{{ user.email }}</td>
                    </tr>
                    <tr>
                        <th>가입일시</th>
                        <td>{{ user.date_joined }}</td>
                    </tr>
                </table>
            </div>

                <h3>내가쓴글</h3>
                <table class="type01">
                    <tr>
                        <th>글제목</th>
                        <th>작성시간</th>
                        <th>수정시간</th>
                    </tr>
                    {% for post in my_posts %}
                    <tr>
                        <td><a href="{% url 'main:detail' post.id %}">{{ post.title }}</a></td>
                        <td><small>{{ post.created_at }}</small></td>
                        <td><small>{{ post.updated_at }}</small></td>
                    </tr>
                    {% endfor %}
                </table>
            </div>

            <div>
                <h3>내가쓴댓글</h3>
                <table class="type01">
                    <thead>
                        <tr>
                            <th>글제목</th>
                            <th>작성시간</th>
                            <th>수정시간</th>
                        </tr>
                    </thead>
                    {% for comment in my_comments %}
                    <tbody>
                        <tr>
                            <td><a href="{% url 'main:detail' comment.post.id %}">{{ comment.post.title }}</a></td>
                            <td><small>{{ comment.created_at }}</small></td>
                            <td><small>{{ comment.updated_at }}</small></td>
                        </tr>
                    </tbody>
                    {% endfor %}
                </table>
            </div>

            <div>
                <h3>나의 스크랩 목록</h3>
                <table class="type01">
                    <thead>
                        <tr>
                            <th>글제목</th>
                            <th>작성시간</th>
                            <th>수정시간</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for post in scrap_posts %}
                        <tr>
                            <td><a href="{% url 'main:detail' post.id %}">{{ post.title }}</a></td>
                            <td><small>{{ post.created_at }}</small></td>
                            <td><small>{{ post.updated_at }}</small></td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
        {% endif %}
    {% endblock %}
</body>

accounts/templates/accounts/edit_mypage.html
{% extends "base.html" %}
{% load static %}

{% block content %}
        <title>프로필 수정</title>
        <link rel="stylesheet" type="text/css" href="{% static 'accounts/about.css' %}">

    <style>
        .change {
            background-color: #daf1de;
            padding: 10px;
            margin-left: 20px;
            margin-right: 20px;
        }

    </style>
    <body>
    <div class="change">
        {{ form.media }}
    <form action="" method="POST">
    {% csrf_token %}
    {% for field in form %}
          {%if field.label != _('이메일') %}
                <div class="content_container">

                {{ field.errors }}
                {{ field.label_tag }}<br> {{ field }}

                </div>
        {% endif %}
    {% endfor %}
    </div>




<div class="button_container">
    <button type="submit" class="btn btn-primary btn-lg">수정</button>
    </div>
    </form>
{% endblock %}
</body>

accounts/templates/accounts/login_form.html
{% load socialaccount %}
{% load myfilters %}
{% load static %}

<head>
    <title>Login</title>
    <meta charset="utf-8">

{#<form action="" method="post">#}
{#    {% csrf_token %}#}
{#    <table>#}
{#        {{ form.as_table }}#}
{#    </table>#}
{#    <input type="submit" />#}
{#</form>#}

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static "accounts/login_form_styles.css" %}"/>
    <title>JOBSSUL</title>
</head>


<body>

<div class="container">
{% if messages %}
  <div class="container">
      {% for message in messages %}
          <div class="alert alert-{{ message.tags }}">
            {{ message.message }}
          </div>
      {% endfor %}
  </div>
{% endif %}


<form action="" method="post">
    {% csrf_token %}
    <div class="login-form">
        {{ form.email|addcss:'text-field'}}
        {{ form.password |addcss:'text-field'}}
        <button class="btn btn-primary submit-btn">로그인</button>
        <button class="btn btn-primary submit-btn" style="margin-top: 10px"><a class="nav-link" style="text-decoration: none; color:white; padding:0px;" href="{% provider_login_url 'google' %}?next={{ request.path }}">GMAIL 계정으로 로그인</a></button>
        <div class="links">
            <a href="{% url 'accounts:signup' %}">아직 회원가입을 안하셨나요?</a><br>
            <a href="#">비밀번호를 잊어버리셨나요?</a>
        </div>
    </div>

</form>
</div>
</body>

accounts/templates/accounts/signup_form.html
{% load socialaccount %}
<!doctype html>
<html lang="en">
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <title>JOBSSUL</title>
  </head>

  <style>
      body {
          background-color: #daf1de;
      }

      .layout {
          display: flex;
          justify-content: center;
      }
  </style>


  <body>
  <div class="container">
    {% if messages %}
          <div class="container">
              {% for message in messages %}
                  <div class="alert alert-{{ message.tags }}">
                    {{ message.message }}
                  </div>
              {% endfor %}
          </div>
    {% endif %}


    <div class ='layout'>
        <form action="" method="post" id="form">
            {% csrf_token %}
                <table>
                    {{ form.as_table }}
                </table>
                <input type="submit"/>
        </form>
    </div>
  <div style="text-align: center">
  <button class="btn btn-primary submit-btn" style="margin-top: 10px"><a class="nav-link" style="text-decoration: none; color:white; padding:0px;" href="{% provider_login_url 'google' %}?next={{ request.path }}">GMAIL 계정으로 로그인</a></button>
  </div>
  </div>
  </body>
</html>