accounts/urls.py
# from allauth.account.views import LoginView
from django.contrib.auth.views import LoginView


from django.conf.urls import url
from django.urls import path
from . import views
from django.conf import settings
from django.contrib.auth import views as auth_views
from .Forms import LoginForm

app_name ='accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    # path('login/', views.login, name='login'),
    path('login/', views.main_login, name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page="main:main"), name='logout'),
    path('mypage', views.mypage, name='user_profile'),
    path('mypage/edit', views.edit_mypage, name='edit_mypage')
]

jobssul/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.shortcuts import render
from django.urls import path, include


urlpatterns = [
    path('main/', include('main.urls', namespace='main')),
    path('admin/', admin.site.urls),

    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('mypage/', include('accounts.urls', namespace='mypage')),
    path('notice/', include('notice.urls', namespace='notice')),
    path('claim/', include('claim.urls', namespace='claim')),
    path('accounts/', include('allauth.urls'))
]

main/urls.py
from django.urls import path, re_path
from . import views
from main.views import main_detail, main_create

app_name='main'

urlpatterns = [
    path('', views.main_page, name='main'),
    path('post/', views.main_post, name='post'),
    path('post/<int:post_pk>/', views.main_detail, name='detail'),
    path('create/', views.main_create, name='create'),
    path('post/<int:post_pk>/edit/', views.main_edit, name='edit'),
    path('post/<int:post_pk>/delete/', views.main_delete , name='delete'),
    path('post/<int:post_pk>/comment/new/', views.comment_new, name='comment_new'),
    path('post/<int:pk>/comment/edit/', views.comment_edit, name='comment_edit'),
    path('post/<int:pk>/comment/delete/', views.comment_delete, name='comment_delete'),
    path('like/', views.like_post, name='like_post'),
    path('best/', views.best_post, name='best_post'),
    # path('post/<int:pk>/comment/like_comment/', views.like_comment, name='like_comment'),
    path('like_comment/', views.like_comment, name='like_comment'),
    path('post/<int:post_pk>/scrap_post/', views.scrap_post, name='scrap_post'),
    path('category/', views.category, name='category')
]

templates/address_widget.html
<body>
    <input type="text" id="sample4_postcode" placeholder="우편번호" readonly>
    <input type="button" onclick="sample4_execDaumPostcode()" value="우편번호 찾기"><br>
    <input type="text"  id="sample4_roadAddress" placeholder="도로명주소" readonly>
    <input type="text" name="reside" id="sample4_jibunAddress" placeholder="지번주소" readonly>
    <span id="guide" style="color:#999"></span>

    <script src="http://dmaps.daum.net/map_js_init/postcode.v2.js"></script>
    <script>
    //본 예제에서는 도로명 주소 표기 방식에 대한 법령에 따라, 내려오는 데이터를 조합하여 올바른 주소를 구성하는 방법을 설명합니다.
        function sample4_execDaumPostcode() {
            new daum.Postcode({
                oncomplete: function(data) {
                // 팝업에서 검색결과 항목을 클릭했을때 실행할 코드를 작성하는 부분.

                // 도로명 주소의 노출 규칙에 따라 주소를 조합한다.
                // 내려오는 변수가 값이 없는 경우엔 공백('')값을 가지므로, 이를 참고하여 분기 한다.
                    var fullRoadAddr = data.roadAddress; // 도로명 주소 변수
                    var extraRoadAddr = ''; // 도로명 조합형 주소 변수

                // 법정동명이 있을 경우 추가한다. (법정리는 제외)
                // 법정동의 경우 마지막 문자가 "동/로/가"로 끝난다.
                   if(data.bname !== '' && /[동|로|가]$/g.test(data.bname)){
                       extraRoadAddr += data.bname;
                    }
                // 건물명이 있고, 공동주택일 경우 추가한다.
                    if(data.buildingName !== '' && data.apartment === 'Y'){
                       extraRoadAddr += (extraRoadAddr !== '' ? ', ' + data.buildingName : data.buildingName);
                    }
                    // 도로명, 지번 조합형 주소가 있을 경우, 괄호까지 추가한 최종 문자열을 만든다.
                    if(extraRoadAddr !== ''){
                        extraRoadAddr = ' (' + extraRoadAddr + ')';
                    }
                    // 도로명, 지번 주소의 유무에 따라 해당 조합형 주소를 추가한다.
                    if(fullRoadAddr !== ''){
                        fullRoadAddr += extraRoadAddr;
                    }

                    // 우편번호와 주소 정보를 해당 필드에 넣는다.
                    document.getElementById('sample4_postcode').value = data.zonecode; //5자리 새우편번호 사용
                    document.getElementById('sample4_roadAddress').value = fullRoadAddr;
                    document.getElementById('sample4_jibunAddress').value = data.jibunAddress;

                    // 사용자가 '선택 안함'을 클릭한 경우, 예상 주소라는 표시를 해준다.
                    if(data.autoRoadAddress) {
                        //예상되는 도로명 주소에 조합형 주소를 추가한다.
                        var expRoadAddr = data.autoRoadAddress + extraRoadAddr;
                        document.getElementById('guide').innerHTML = '(예상 도로명 주소 : ' + expRoadAddr + ')';

                    } else if(data.autoJibunAddress) {
                        var expJibunAddr = data.autoJibunAddress;
                        document.getElementById('guide').innerHTML = '(예상 지번 주소 : ' + expJibunAddr + ')';

                    } else {
                        document.getElementById('guide').innerHTML = '';
                    }
                }
            }).open();
        }
    </script>
</body>

templates/base.html
{% extends "header.html" %}
{% load static %}

{% block below_nav %}


    <script type="text/javascript">
    $(document).ready(function(event){
        $(document).ready(function(event){
            $('.reply-btn').click(function() {
                $(this).parent().next('.replied-comments').fadeToggle()
            });
        });

        $(document).on('click', '#like', function(event){
            event.preventDefault();
            var pk = $(this).attr('value');
            $.ajax({
                type: 'POST',
                url: '{% url "main:like_post" %}',
                data: {'id':pk, 'csrfmiddlewaretoken': '{{ csrf_token }}'},
                dataType: 'json',
                success: function(response){
                    $('#like-section').html(response['form'])
                    console.log($('#like-section').html(response['form']));
                },
                error: function(rs, e){
                    console.log(rs.responseText);
                },
            });
        });
    });




        $(document).on('click', '.comment_like', function(event){
            event.preventDefault();
            var pk = $(this).attr('value');
            $.ajax({
                type: 'POST',
                url: '{% url "main:like_comment" %}',
                data: {'comment_id':pk, 'csrfmiddlewaretoken': '{{ csrf_token }}'},
                dataType: 'json',
                success: function(response){
                    $('#comment_like_section'+pk).html(response['form'])
                },
                error: function(rs, e){
                    console.log(rs.responseText);
                },
            });
        });

   $(document).on('submit', '.comment-form', function(event){
        event.preventDefault();
        console.log($(this).serialize());
        $.ajax({
            type: 'POST',
            url: $(this).attr('action'),
            data: $(this).serialize(),
            dataType: 'json',
            success: function(response) {
                $('.main-comment-section').html(response['form']);
                $('textarea').val('');
                $('.reply-btn').click(function() {
                    $(this).parent().next('.replied-comments').fadeToggle()
                    $('textarea').val('');
                });
            },
            error: function (rs, e) {
                console.log(rs.responseText);
            },
        })
    });

   $(document).on('submit', '.reply-form', function(event){
        event.preventDefault();
        console.log($(this).serialize());
        $.ajax({
            type: 'POST',
            url: $(this).attr('action'),
            data: $(this).serialize(),
            dataType: 'json',
            success: function(response) {
                $('.main-comment-section').html(response['form']);
                $('textarea').val('');
                $('.reply-btn').click(function() {
                    $(this).parent().next('.replied-comments').fadeToggle()
                    $('textarea').val('');
                });
            },
            error: function (rs, e) {
                console.log(rs.responseText);
            },
        })
    });



</script>

  <style>
      @import url('https://fonts.googleapis.com/css?family=Stylish');
      .main_header{
          font-family: 'Stylish', sans-serif;
          height: 60px;
          width: 100%;
          padding-bottom: 30px;
          margin: 0;
          text-align: center;
          font-size: 50px;
          font-weight: 400;
          background-color: white;
      }
      .design {
          background-color: #e0f0ed;
          padding-top: 10px;
          padding-bottom: 10px;
          margin-bottom: 30px;
      }
      .text-center{
          margin-bottom: 30px;
      }
 </style>

<body>

    <div class="text-center">
        <img src="{% static "main/banner.png" %}" class="rounded img-fluid" alt="Responsive image" />
    </div>
        <div class="design">
            <h3 class="main_header">모든 알바 후기가 모이는 곳</h3>
        </div>
    {% if messages %}
      <div class="container">
          {% for message in messages %}
              <div class="alert alert-{{ message.tags }}">
                {{ message.message }}
              </div>
          {% endfor %}
      </div>
    {% endif %}


  {% block content %}
  {% endblock %}

</body>

{% endblock %}

templates/header.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">

  <title>JOBSSUL</title>
  </head>


<style>
    @import url('https://fonts.googleapis.com/css?family=Yeon+Sung');
    @font-face{
        src: url("../main/static/font/BinggraeTaom-Bold.otf");
        font-family: "Taom";
    }
    .navbar {
        padding: 10px 20px;
        font-family: 'Taom', sans-serif;
    }

    .navbar .nav-item{
        float: left;
        display: block;
        text-align: center;
        padding: 12px 14px;
        font-size: 17px;
        border-bottom: 3px solid transparent;
        border-radius: 0;
    }

    a {
        color: #85d4be;
        font-weight: 500;
    }

    a:hover{
        color: #85d4be;
        font-weight: bold;
    }


    .navbar .nav-item:hover{
        background-color: #f2f2f2;
        border-bottom: 3px solid #aee6cb;
    }

    .navbar .nav-item:active{
        border-bottom: 3px solid #aee6cb;
    }

    #inputState{
        border-color: #aee6cb;
    }

    #info{
        float: right;
    }

    .button{
        border-color: #aee6cb;
        background-color: white;
        color: #aee6cb;
    }

    .button:hover{
        background-color: #aee6cb;
        border-color: #aee6cb;
    }

    .collapse {
        justify-content: flex-end;
    }

    .search_nav {
        display: flex;
        justify-content: center;
    }


</style>

<body>
    <nav class="navbar navbar-expand-lg navbar-light" style="background-color: white;" >
      <a href="{% url "main:main" %}">
        <img src={% static "main/logo.png"%} width="119" height="44" alt="" style="padding: 0;">
      </a>

{#    <form class="form-inline my-2 mr-2 ml-2 my-lg-0" action="{% url 'main:post' %}">#}
{#          <input class="form-control mr-sm-2" type="search" placeholder="검색" aria-label="Search" name="q">#}
{#          <button class="btn btn-outline-success my-2 my-sm-0 button" type="submit">Search</button>#}
{#    </form>#}

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <div class="row align-items-center justify-content-center" style="width:50%; min-width: 700px;">

                            <form method="POST" action="{% url "main:category" %}" class="search_nav">
                                {% csrf_token %}
                                <div class="col-md-2 pt-3">
                                   <div class="form-group">
{#                                   <div class="form-group search-box">#}
                                      <select id="inputState " class="form-control" name="place">
                                        <option selected value="0">지역</option>
                                        <option value="강남/서초/양재">강남/서초/양재</option>
                                        <option value="잠실/송파/강동">잠실/송파/강동</option>
                                        <option value="동작/관악/사당">동작/관악/사당</option>
                                        <option value="마포/서대문/은평">마포/서대문/은평</option>
                                        <option value="종로/중구/용산">종로/중구/용산</option>
                                        <option value="노원/도봉/강북/성북">노원/도봉/강북/성북</option>
                                        <option value="광진/성동/중랑/동대문">광진/성동/중랑/동대문</option>
                                        <option value="영등포/구로/신도림">영등포/구로/신도림</option>
                                        <option value="강서/금천/양천">강서/금천/양천</option>
                                      </select>
                                   </div>
                                </div>
                                <div class="col-md-2 pt-3">
                                   <div class="form-group">
                                      <select id="inputState" class="form-control" name="type">
                                        <option selected value="0">직종</option>
                                        <option value="전체">전체</option>
                                        <option value="외식/음료">외식/음료</option>
                                        <option value="유통/판매">유통/판매</option>
                                        <option value="문화/여가/생활">문화/여가/생활</option>
                                        <option value="서비스">서비스</option>
                                        <option value="사무직">사무직</option>
                                        <option value="고객상담/리서치/영업">고객상담/리서치/영업</option>
                                        <option value="생산/건설/노무">생산/건설/노무</option>
                                        <option value="IT/컴퓨터">IT/컴퓨터</option>
                                        <option value="교육/강사">교육/강사</option>
                                        <option value="디자인">디자인</option>
                                        <option value="미디어">미디어</option>
                                        <option value="운전/배달">운전/배달</option>
                                        <option value="병원/간호/연구">병원/간호/연구</option>
                                      </select>
                                   </div>
                                </div>
                                <div class="col-md-2 pt-3">
                                    <div class="form-group">
                                      <select id="inputState" class="form-control" name="pay">
                                        <option selected value="0">시급</option>
                                        <option value="전체">전체</option>
                                        <option value="7500원~9000원">7500원~9000원</option>
                                        <option value="9000원~10500원">9000원~10500원</option>
                                        <option value="10500원 이상">10500원 이상</option>
                                      </select>
                                    </div>
                                </div>
                                <div class="col-md-2 pt-3">
                                   <button type="submit" class="btn btn-primary btn-block button">검색</button>
                                </div>
                            </form>
            </div>


          {% comment %}  <ul class="nav nav-pills nav-justified">

            </ul>{% endcomment %}

            <ul id="info" class="nav nav-pills" style="min-width: 400px">
             <li class="nav-item">
                <a class="nav-link" href="{% url 'notice:main' %}" style="padding:0px">공지썰 <span class="sr-only">(current)</span></a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'claim:main' %}"style="padding:0px">건의썰</a>
              </li>
                    {% if not user.is_authenticated %}
                        <li class="nav-item"><a class="nav-link" href="{% url "accounts:signup" %}"style="padding:0px">회원가입</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url "accounts:login" %}?next={{ request.path }}"style="padding:0px">로그인</a></li>
                    {% else %}
                        <li class="nav-item"><a class="nav-link" href="{% url "accounts:user_profile" %}"style="padding:0px">마이페이지</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url "accounts:logout" %}?next={{ request.path }}"style="padding:0px">로그아웃</a></li>
                    {% endif %}
            </ul>
      </div>
    </nav>

    {% block below_nav %}
    {% endblock %}

</body>

templates/map_widget.html
<head>
   <style>
    .map_wrap, .map_wrap * {margin:0;padding:0;font-family:'Malgun Gothic',dotum,'돋움',sans-serif;font-size:12px;}
    .map_wrap a, .map_wrap a:hover, .map_wrap a:active{color:#000;text-decoration: none;}
    .map_wrap {position:relative;width:100%;height:500px;}
    #menu_wrap {position:absolute;top:0;left:0;bottom:0;width:250px;margin:10px 0 30px 10px;padding:5px;overflow-y:auto;background:rgba(255, 255, 255, 0.7);z-index: 1;font-size:12px;border-radius: 10px;}
    .bg_white {background:#fff;}
    #menu_wrap hr {display: block; height: 1px;border: 0; border-top: 2px solid #5F5F5F;margin:3px 0;}
    #menu_wrap .option{text-align: center;}
    #menu_wrap .option p {margin:10px 0;}
    #menu_wrap .option button {margin-left:5px;}
    #placesList li {list-style: none;}
    #placesList .item {position:relative;border-bottom:1px solid #888;overflow: hidden;cursor: pointer;min-height: 65px;}
    #placesList .item span {display: block;margin-top:4px;}
    #placesList .item h5, #placesList .item .info {text-overflow: ellipsis;overflow: hidden;white-space: nowrap;}
    #placesList .item .info{padding:10px 0 10px 55px;}
    #placesList .info .gray {color:#8a8a8a;}
    #placesList .info .jibun {padding-left:26px;background:url(http://t1.daumcdn.net/localimg/localimages/07/mapapidoc/places_jibun.png) no-repeat;}
    #placesList .info .tel {color:#009900;}
    #placesList .item .markerbg {float:left;position:absolute;width:36px; height:37px;margin:10px 0 0 10px;background:url(http://t1.daumcdn.net/localimg/localimages/07/mapapidoc/marker_number_blue.png) no-repeat;}
    #placesList .item .marker_1 {background-position: 0 -10px;}
    #placesList .item .marker_2 {background-position: 0 -56px;}
    #placesList .item .marker_3 {background-position: 0 -102px}
    #placesList .item .marker_4 {background-position: 0 -148px;}
    #placesList .item .marker_5 {background-position: 0 -194px;}
    #placesList .item .marker_6 {background-position: 0 -240px;}
    #placesList .item .marker_7 {background-position: 0 -286px;}
    #placesList .item .marker_8 {background-position: 0 -332px;}
    #placesList .item .marker_9 {background-position: 0 -378px;}
    #placesList .item .marker_10 {background-position: 0 -423px;}
    #placesList .item .marker_11 {background-position: 0 -470px;}
    #placesList .item .marker_12 {background-position: 0 -516px;}
    #placesList .item .marker_13 {background-position: 0 -562px;}
    #placesList .item .marker_14 {background-position: 0 -608px;}
    #placesList .item .marker_15 {background-position: 0 -654px;}
    #pagination {margin:10px auto;text-align: center;}
    #pagination a {display:inline-block;margin-right:10px;}
    #pagination .on {font-weight: bold; cursor: default;color:#777;}
</style>
</head>



<body>
    <input name='zizum' type="text" id="zizum">
    <input name="reside" type="text" id="doro">

    <div class="map_wrap">
        <div id="map" style="width:800px;height:500px;position:relative;overflow:hidden;"></div>
        <div id="menu_wrap" class="bg_white">
            <div class="option">
                <div>
                        키워드 : <input type="text" id="keyword" size="15">
                        <input type="submit" value="검색" onclick="searchPlaces(); return false">
                </div>
            </div>
            <hr>
            <ul id="placesList"></ul>
            <div id="pagination"></div>
        </div>
    </div>


<script type="text/javascript" src="//dapi.kakao.com/v2/maps/sdk.js?appkey=cc803382838eb7e8676cf20cda8076a7&libraries=services"></script>

<script>
// 마커를 담을 배열입니다
var markers = [];

var mapContainer = document.getElementById('map'), // 지도를 표시할 div
    mapOption = {
        center: new daum.maps.LatLng(37.566826, 126.9786567), // 지도의 중심좌표
        level: 3 // 지도의 확대 레벨
    };

// 지도를 생성합니다
var map = new daum.maps.Map(mapContainer, mapOption);

// 장소 검색 객체를 생성합니다
var ps = new daum.maps.services.Places();

// 검색 결과 목록이나 마커를 클릭했을 때 장소명을 표출할 인포윈도우를 생성합니다
var infowindow = new daum.maps.InfoWindow({zIndex:1});

{#var road = new places.road_address_name;#}

// 키워드로 장소를 검색합니다
searchPlaces();

// 키워드 검색을 요청하는 함수입니다
function searchPlaces() {

    var keyword = document.getElementById('keyword').value;

    {#if (!keyword.replace(/^\s+|\s+$/g, '')) {#}
    {#    alert('키워드를 입력해주세요!');#}
    {#    return false;#}
    {##}

    // 장소검색 객체를 통해 키워드로 장소검색을 요청합니다
    ps.keywordSearch( keyword, placesSearchCB);
}

// 장소검색이 완료됐을 때 호출되는 콜백함수 입니다
function placesSearchCB(data, status, pagination) {
    if (status === daum.maps.services.Status.OK) {

        // 정상적으로 검색이 완료됐으면
        // 검색 목록과 마커를 표출합니다
        displayPlaces(data);

        // 페이지 번호를 표출합니다
        displayPagination(pagination);

    } else if (status === daum.maps.services.Status.ZERO_RESULT) {

        alert('검색 결과가 존재하지 않습니다.');
        return;

    } else if (status === daum.maps.services.Status.ERROR) {

        alert('검색 결과 중 오류가 발생했습니다.');
        return;

    }
}

// 검색 결과 목록과 마커를 표출하는 함수입니다
function displayPlaces(places) {
    var listEl = document.getElementById('placesList'),
    menuEl = document.getElementById('menu_wrap'),
    fragment = document.createDocumentFragment(),
    bounds = new daum.maps.LatLngBounds(),
    listStr = '';

    // 검색 결과 목록에 추가된 항목들을 제거합니다
    removeAllChildNods(listEl);

    // 지도에 표시되고 있는 마커를 제거합니다
    removeMarker();

    for ( var i=0; i<places.length; i++ ) {

        // 마커를 생성하고 지도에 표시합니다
        var placePosition = new daum.maps.LatLng(places[i].y, places[i].x),
            marker = addMarker(placePosition, i),
            itemEl = getListItem(i, places[i]); // 검색 결과 항목 Element를 생성합니다

        // 검색된 장소 위치를 기준으로 지도 범위를 재설정하기위해
        // LatLngBounds 객체에 좌표를 추가합니다
        bounds.extend(placePosition);

        // 마커와 검색결과 항목에 mouseover 했을때
        // 해당 장소에 인포윈도우에 장소명을 표시합니다
        // mouseout 했을 때는 인포윈도우를 닫습니다
        (function(marker, title, road) {
            daum.maps.event.addListener(marker, 'mouseover', function() {
                displayInfowindow(marker, title);
            });

            daum.maps.event.addListener(marker, 'mouseout', function() {
                infowindow.close();
            });

            daum.maps.event.addListener(marker, 'click', function() {
                readInfo(marker, title, road);
            });

            itemEl.onmouseover =  function () {
                displayInfowindow(marker, title, road);
            };

            itemEl.onmouseout =  function () {
                infowindow.close();
            };



        })(marker, places[i].place_name, places[i].address_name);

        fragment.appendChild(itemEl);
    }

    // 검색결과 항목들을 검색결과 목록 Elemnet에 추가합니다
    listEl.appendChild(fragment);
    menuEl.scrollTop = 0;

    // 검색된 장소 위치를 기준으로 지도 범위를 재설정합니다
    map.setBounds(bounds);
}

// 검색결과 항목을 Element로 반환하는 함수입니다
function getListItem(index, places) {

    var el = document.createElement('li'),
    itemStr = '<span class="markerbg marker_' + (index+1) + '"></span>' +
                '<div class="info">' +
                '   <h5>' + places.place_name + '</h5>';

    if (places.road_address_name) {
        itemStr += '    <span>' +  places.road_address_name+ '</span>' +
                    '   <span class="jibun gray">' +  places.address_name  + '</span>';
    } else {
        itemStr += '    <span>' +  places.address_name  + '</span>';
    }

      {#itemStr += '  <span class="tel">' + places.phone  + '</span>' +#}
      {#          '</div>';#}

    el.innerHTML = itemStr;
    el.className = 'item';

    return el;
}

// 마커를 생성하고 지도 위에 마커를 표시하는 함수입니다
function addMarker(position, idx, title) {
    var imageSrc = 'http://t1.daumcdn.net/localimg/localimages/07/mapapidoc/marker_number_blue.png', // 마커 이미지 url, 스프라이트 이미지를 씁니다
        imageSize = new daum.maps.Size(36, 37),  // 마커 이미지의 크기
        imgOptions =  {
            spriteSize : new daum.maps.Size(36, 691), // 스프라이트 이미지의 크기
            spriteOrigin : new daum.maps.Point(0, (idx*46)+10), // 스프라이트 이미지 중 사용할 영역의 좌상단 좌표
            offset: new daum.maps.Point(13, 37) // 마커 좌표에 일치시킬 이미지 내에서의 좌표
        },
        markerImage = new daum.maps.MarkerImage(imageSrc, imageSize, imgOptions),
            marker = new daum.maps.Marker({
            position: position, // 마커의 위치
            image: markerImage
        });

    marker.setMap(map); // 지도 위에 마커를 표출합니다
    markers.push(marker);  // 배열에 생성된 마커를 추가합니다

    return marker;
}

// 지도 위에 표시되고 있는 마커를 모두 제거합니다
function removeMarker() {
    for ( var i = 0; i < markers.length; i++ ) {
        markers[i].setMap(null);
    }
    markers = [];
}

// 검색결과 목록 하단에 페이지번호를 표시는 함수입니다
function displayPagination(pagination) {
    var paginationEl = document.getElementById('pagination'),
        fragment = document.createDocumentFragment(),
        i;

    // 기존에 추가된 페이지번호를 삭제합니다
    while (paginationEl.hasChildNodes()) {
        paginationEl.removeChild (paginationEl.lastChild);
    }

    for (i=1; i<=pagination.last; i++) {
        var el = document.createElement('a');
        el.href = "#";
        el.innerHTML = i;

        if (i===pagination.current) {
            el.className = 'on';
        } else {
            el.onclick = (function(i) {
                return function() {
                    pagination.gotoPage(i);
                }
            })(i);
        }

        fragment.appendChild(el);
    }
    paginationEl.appendChild(fragment);
}

// 검색결과 목록 또는 마커를 클릭했을 때 호출되는 함수입니다
// 인포윈도우에 장소명을 표시합니다
function displayInfowindow(marker, title) {
    var content = '<div style="padding:5px;z-index:1;">' + title + '</div>';

    infowindow.setContent(content);
    infowindow.open(map, marker);
}

function readInfo(marker, title, road) {
    document.getElementById('zizum').value = title;
    document.getElementById('doro').value = road;
}

 // 검색결과 목록의 자식 Element를 제거하는 함수입니다
function removeAllChildNods(el) {
    while (el.hasChildNodes()) {
        el.removeChild (el.lastChild);
    }
}

    </script>
</body>