jobssul/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.shortcuts import render
from django.urls import path, include


urlpatterns = [
    path('main/', include('main.urls', namespace='main')),
    path('admin/', admin.site.urls),

    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('mypage/', include('accounts.urls', namespace='mypage')),
    path('notice/', include('notice.urls', namespace='notice')),
    path('claim/', include('claim.urls', namespace='claim')),
    path('accounts/', include('allauth.urls'))
]

main/urls.py
from django.urls import path, re_path
from . import views
from main.views import main_detail, main_create

app_name='main'

urlpatterns = [
    path('', views.main_page, name='main'),
    path('post/', views.main_post, name='post'),
    path('post/<int:post_pk>/', views.main_detail, name='detail'),
    path('create/', views.main_create, name='create'),
    path('post/<int:post_pk>/edit/', views.main_edit, name='edit'),
    path('post/<int:post_pk>/delete/', views.main_delete , name='delete'),
    path('post/<int:post_pk>/comment/new/', views.comment_new, name='comment_new'),
    path('post/<int:pk>/comment/edit/', views.comment_edit, name='comment_edit'),
    path('post/<int:pk>/comment/delete/', views.comment_delete, name='comment_delete'),
    path('like/', views.like_post, name='like_post'),
    path('best/', views.best_post, name='best_post'),
    # path('post/<int:pk>/comment/like_comment/', views.like_comment, name='like_comment'),
    path('like_comment/', views.like_comment, name='like_comment'),
    path('post/<int:post_pk>/scrap_post/', views.scrap_post, name='scrap_post'),
    path('category/', views.category, name='category')
]

main/models.py
from django.core.validators import MinLengthValidator, MaxValueValidator, MinValueValidator
from datetime import timezone
from django.db import models
import django
from django.urls import reverse
from jobssul import settings
from accounts.models import User


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager, self).get_queryset().filter(status='published')
#     user_for_related_fields = True
#
#     def published(self, **kwargs):
#         return self.filter(status='published', **kwargs)


class Post(models.Model):
    objects = models.Manager()
    published = PublishedManager()
    PAYMENT_LEVEL = (
        ('7500원~9000원', '7500원~9000원'),
        ('9000원~10500원', '9000원~10500원'),
        ('10500원 이상', '10500원 이상'),
    )


    WORK_TYPE = (
        ('외식/음료', '외식/음료'),
        ('유통/판매', '유통/판매'),
        ('문화/여가/생활', '문화/여가/생활'),
        ('서비스', '서비스'),
        ('사무직', '사무직'),
        ('고객상담/리서치/영업', '고객상담/리서치/영업'),
        ('생산/건설/노무', '생산/건설/노무'),
        ('IT/컴퓨터', 'IT/컴퓨터'),
        ('교육/강사', '교육/강사'),
        ('디자인', '디자인'),
        ('미디어', '미디어'),
        ('운전/배달', '운전/배달'),
        ('병원/간호/연구', '병원/간호/연구'),
    )

    author = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    title = models.CharField(max_length=20, verbose_name= '제목')
    content = models.TextField(verbose_name='내용', validators=[MinLengthValidator(10, message=None)],
                               help_text='내용을 최소 10자 이상으로 작성해주세요')
    payment = models.CharField(max_length=20, choices=PAYMENT_LEVEL, verbose_name='시급')
    # zizum = models.TextField(max_length=50, verbose_name='지점', null=True, help_text='지점을 검색하여 지도에 나온 마커를 클릭해 지점을 선택해주세요.')

    reside = models.TextField(max_length=50, verbose_name='지점', null=True, help_text='지점을 검색하여 지도에 나온 마커를 클릭해 지점을 선택해주세요.')
    recommend = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(5)], verbose_name = '별점')
    work_type = models.CharField(max_length=20, choices=WORK_TYPE, verbose_name='직종', help_text='알바 직종을 선택해 주세요.')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    likes = models.ManyToManyField(User, related_name='likes', blank=True)
    status = models.CharField(max_length=10, default='published')
    scrap = models.ManyToManyField(User, related_name='scrap', blank=True)

    class Meta:
        ordering = ['-id']

    # created_at = models.DateTimeField(auto_now_add=True)
    # updated_at = models.DateTimeField(auto_now = True)

    # def published(self):
    #     now = timezone.now()
    #     return now

    def __str__(self):
        template = '{0.title} {0.author}'
        return template.format(self)

    def edit_post_url(self):
        return reverse('main:edit', args=[self.pk])

    def delete_post_url(self):
        return reverse('main:delete', args=[self.pk])

    def total_likes(self):
        return self.likes.count()

    def get_absolute_url(self):
        return reverse('main:detail', args=[self.pk])


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    reply = models.ForeignKey('Comment', null=True, related_name='replies', on_delete=models.CASCADE)
    likes = models.ManyToManyField(User, related_name='comment_likes', blank=True)



    def get_edit_url(self):
        return reverse('main:comment_edit', args=[self.pk])

    def get_delete_url(self):
        return reverse('main:comment_delete', args=[self.pk])

    def get_absolute_url(self):
        return reverse('main:detail', args=[self.pk])

    def comment_total_likes(self):
        return self.likes.count()

main/forms.py
from django import forms
from django.core.validators import MinLengthValidator

from .models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = '__all__'
        exclude = ['likes']


class CommentForm(forms.ModelForm):
    message = forms.CharField(label="", widget=forms.Textarea(attrs={'class': 'form-control', 'placeholder': '내용을 입력하세요!', 'rows': '4', 'cols': '50'}))
    class Meta:
        model = Comment
        fields = ['message']

main/views.py
from itertools import chain

from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.template import RequestContext
from django.urls import reverse_lazy
from django.views.decorators.http import require_POST

from accounts.models import User
from .Forms import CommentForm
from .models import Post, Comment
from .Forms import PostForm
from django.db.models import Q, Count, QuerySet
from django.template.loader import render_to_string
from django.http import JsonResponse




def main_page(request):
    posts = Post.objects.all()
    users = User.objects.all()
    recommend_posts = set()
    if request.user.is_authenticated:
        try:
            for user in users:
                if user.reside:
                    user_reside_list = request.user.reside.split(' ')
                    if user_reside_list:
                        recommend_posts = Post.objects.filter(
                            Q(reside__icontains=user_reside_list[0]) and
                            Q(reside__icontains=user_reside_list[1]) or
                            Q(reside__icontains=user_reside_list[2])
                    )
        except ValueError or TypeError:
            pass

          # posts = Post.objects.all().order_by('-updated_at')
    data = {
        'posts': posts,
        'latest': posts.order_by('-updated_at'),
        'liked': posts.annotate(liked=Count('likes')).order_by('-liked'),
        'recommend_posts': recommend_posts,

    }
    return render(request, 'main/main.html', data)


def main_post(request):
    # post = Post.objects.all()
    posts = Post.published.all()
    query = request.GET.get('q', None)
    # comments = Comment.objects.filter()
    if query:
        posts = Post.objects.filter(
            Q(title__icontains=query) |
            Q(author__username=query) |
            Q(content__icontains=query)
            )
    data = {
        # 'post': post,
        'posts': posts,
        # 'comments': comments,
    }
    return render(request, 'main/post.html', data)


def main_detail(request, post_pk):
    post = Post.objects.get(pk=post_pk)
    form = PostForm()

    comments = Comment.objects.filter(post=post, reply=None).order_by('-id')

    is_liked = False
    if post.likes.filter(id=request.user.id).exists():
        is_liked = True

    is_scrap = False
    if post.scrap.filter(id=request.user.id).exists():
        is_scrap = True

    comment_form = CommentForm()

    if request.method == 'POST':
        comment_form = CommentForm(request.POST or None)
        if comment_form.is_valid():
            message = request.POST.get('message')
            reply_id = request.POST.get('comment_id')
            comment_qs = None

            if reply_id:
                comment_qs = Comment.objects.get(id=reply_id)

            comment = Comment.objects.create(post=post, author=request.user, message=message, reply=comment_qs)
            comment.save()
            # return HttpResponseRedirect(post.get_absolute_url())
        else:
            comment_form = CommentForm()

    # comment = get_object_or_404(Comment, id=request.POST.get('comment_id'))
    # comment_is_liked = False
    # for comment in comments:
    #     comment = comments.get()
    #     if comment.likes.filter(id=request.user.id).exists():
    #         comment_is_liked = True
    # comment = get_object_or_404(Comment, id=request.POST.get('comment_id'))

    comment_is_liked = False
    for comment in comments:
        # comment_is_liked = False
        if comment.likes.filter(id=request.user.id).exists():
            comment_is_liked = True
    data = {
        'post': post,
        'is_liked': is_liked,
        'total_likes': post.total_likes(),
        'comments': comments,
        'comment_form': comment_form,
        'comment_is_liked': comment_is_liked,
        'form': form,
        'is_scrap': is_scrap,

        # 'comment': comment,
    }

    if request.is_ajax():
        html = render_to_string('main/comments.html', data, request=request)
        return JsonResponse({'form': html})
    return render(request, 'main/detail.html', data)


def scrap_post(request, post_pk):
    post = get_object_or_404(Post, pk=post_pk)
    if post.scrap.filter(pk=request.user.id).exists():
        post.scrap.remove(request.user)
        is_scrap = False
    else:
        post.scrap.add(request.user)
        is_scrap = True

    data = {
        'is_scrap': is_scrap,
        'post': post,
    }

    if request.is_ajax():
        html = render_to_string('main/scrap.html', data, request=request)
        return JsonResponse({'form': html})


def like_post(request):
    # post = get_object_or_404(Post, id=request.POST.get('post_id'))
    post = get_object_or_404(Post, id=request.POST.get('id'))
    is_liked = False
    if post.likes.filter(id=request.user.id).exists():
        post.likes.remove(request.user)
        is_liked = False
    else:
        post.likes.add(request.user)
        is_liked = True
    data = {
        'post': post,
        'is_liked': is_liked,
        'total_likes': post.total_likes(),
    }
    if request.is_ajax():
        html = render_to_string('main/like_section.html', data, request=request)
        return JsonResponse({'form': html})



def like_comment(request):
    # comment = get_object_or_404(Comment, id=request.POST.get('id'))
    comment = get_object_or_404(Comment, id=request.POST.get('comment_id'))
    comment_is_liked = False
    if comment.likes.filter(id=request.user.id).exists():
        comment.likes.remove(request.user)
        comment_is_liked = False
    else:
        comment.likes.add(request.user)
        comment_is_liked = True
        # return redirect(f'/main/post/{comment.post.pk}')
    # return redirect(f'/main/post/{comment.post.pk}')
    data = {
        'comment': comment
    }
    html = render_to_string('main/like_comment.html', data, request=request)
    return JsonResponse({'form': html})
    # return HttpResponseRedirect(comment.get_absolute_url())

@login_required
def main_create(request):
    if request.method == 'POST':
        form = PostForm(request.POST, request=request)
        if form.is_valid():
            form.save_create()
            messages.info(request, '새 글이 등록되었습니다.')
            return redirect('main:post')
    else:
        form = PostForm(initial={'author': request.user})
    return render(request, 'main/create.html', {
        'form': form
    })

@login_required
def main_edit(request, post_pk):
    post = get_object_or_404(Post, pk=post_pk)
    # if post.author != request.user:
    #     return redirect(f'/main/post/{post.pk}')
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES, instance=post)
        if form.is_valid():
            print('ok')
            post = form.save()

            return redirect(f'/main/post/{post.pk}')
    else:
        form = PostForm(instance=post)

    return render(request, 'main/edit.html', {
        'form': form,

    })


@login_required
def main_delete(request, post_pk):
    post = get_object_or_404(Post, pk=post_pk)
    if post.author != request.user:
        return redirect(f'/main/post/{post.pk}')

    if request.method == "POST":
        post.delete()
        return redirect('main:post')

    return render(request, 'main/delete.html', {
        'post': post
    })

@login_required
def comment_new(request, post_pk):
    post = get_object_or_404(Post, pk=post_pk)
    if request.method == 'POST':
        form = CommentForm(request.POST, request.FILES)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.author = request.user
            comment.save()
            messages.success(request, '댓글이 작성되었습니다.')
            return redirect('main:detail', post.pk)
    else:
        form = CommentForm()

    return render(request, 'main/comment_form.html', {
        'form': form,
    })

                  # , context_instance=RequestContext)


@login_required
def comment_edit(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    if comment.author != request.user:
        return redirect(f'/main/post/{comment.post.pk}') # '/main/post/{0}/'.format(comment.post.pk)
    if request.method == 'POST':
        form = CommentForm(request.POST, request.FILES, instance=comment)
        if form.is_valid():
            comment = form.save()
            messages.success(request, '댓글이 수정되었습니다.')
            return redirect(f'/main/post/{comment.post.pk}')
    else:
        form = CommentForm(instance=comment)
    return render(request, 'main/comment_form.html', {
        'form': form,
    })


@login_required
def comment_delete(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    if comment.author != request.user:
        return redirect(f'/main/post/{comment.post.pk}')

    if request.method == 'POST':
        comment.delete()
        messages.error(request, '댓글이 삭제되었습니다.')
        return redirect(f'/main/post/{comment.post.pk}')

    return render(request, 'main/comment_confirm_delete.html', {
        'comment': comment,
    })


def best_post(request):
    posts = Post.objects.all()
    # posts = Post.objects.filter.order_by('-likes', '-updated_at')

    return render(request, 'main/best_post.html', {
        'posts': posts
    })


def category(request):
        posts = Post.objects.all()
        place = request.POST.get('place', '0')
        type = request.POST.get('type', '0')
        pay = request.POST.get('pay', '0')

        if place == '0' or type == '0' or pay == '0':
            messages.error(request, '세 카테고리를 모두 선택해주세요')
            return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))
        #조건들 선택안하고 그냥 누르면 request한 그 해당 페이지 리턴

        list1 = place.split('/')
        result = set()
        if place:
            for point in list1:

main/templates/main/category_list.html
{% extends 'base.html' %}

{% block content %}

        {% load static %}

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">


    <style>

    .entire {
        background-color: #daf1de;
    }
    .post_list_container{
        margin-top: 30px;
        margin-left: 50px;
        margin-right: 50px;
        background-color: white;
    }

    .create_post_button{
        text-decoration: none;
        color: white;
        margin-right: 50px;


    }

    #recommend_star{
        height: 16px;
    }
    .create_post_button_container{
            text-align: right;
            margin-bottom: 50px;
        }

    .category{
        text-decoration: none;
        font-weight: 700;
        color: black;
    }

    .d6 {
        text-align: right;
        margin-right: 50px;
    }

    .d6 form {
      height: 42px;
    }
    .d6 input {
      height: 100%;
      width: 0;
      padding: 0 42px 0 15px;
      border: none;
      border-bottom: 2px solid transparent;
      outline: none;
      background: transparent;
      transition: .4s cubic-bezier(0, 0.8, 0, 1);
    }
    .d6 input:focus {
      width: 300px;
      z-index: 1;
      border-bottom: 2px solid white;
    }
    .d6 button {
      background: #B6DCB6;
      border: none;
      height: 42px;
      width: 42px;
      cursor: pointer;
    }
    .d6 button:before {
      content: "\f002";
      font-family: FontAwesome;
      font-size: 16px;
      color: white;
    }
    </style>

    {% if not posts %}
        <div class="container-fluid">
            <div class="alert alert-warning">
                해당하는 포스팅이 없습니다.
            </div>
        </div>
    {% endif %}

     {% if posts %}
        <div class="container-fluid">
            <div class="alert alert-success">
                설정한 조건의 포스팅이 검색되었습니다.
            </div>
        </div>
    {% endif %}

    <div class="d6">
        <form>
          <input type="text" placeholder="검색어 입력" name="q">
          <button type="submit"></button>
        </form>
    </div>



    <div class="entire">
        <div class="post_list_container">
        <table class="table table-bordered table-hover">
          <thead class = "thread-dark">
            <tr>
              <th scope="col">제목</th>
              <th scope="col">작성자</th>
              <th scope="col">별점</th>
            </tr>
          </thead>

          <tbody>

          {% for post in posts %}
            <tr>
              <td><a href="{% url 'main:detail' post.id %}" class="category">{{ post.title }}</a></td>
                <td>{{ post.author.nickname }}</td>
              <td><img id=recommend_star src="{% static 'main/star.jpg' %}"> {{ post.recommend }}</td>
            </tr>
            {% empty %}
          {% endfor %}

          </tbody>
        </table>
        </div>
        <div class="create_post_button_container">
            <a href="{% url 'main:create' %}" class="btn btn-dark btn btn-primary btn-lg create_post_button">게시글 생성</a>
        </div>
    </div>

{% endblock %}

main/templates/main/comment_confirm_delete.html
<form action="" method="post">
    {% csrf_token %}
    정말 삭제하시겠습니까?
    <input type="submit" value="삭제하겠습니다."/>
</form>

main/templates/main/comment_form.html
{#<style>#}
{#body {#}
{#    font-size: 50px;#}
{#}#}
{#</style>#}

<body>
{% block message %}
<form id="comment-edit" action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit"/>
</form>
{% endblock %}
</body>

main/templates/main/comments.html
<style>
    .comment-like {
        margin-top: 20px;
    }
    #comment-container {
        background: #d9f1f1;
        margin-right: 90px;
    }

    #comment {
        border-top: dashed lightgrey 5px;
        padding: 20px;
    }

    #comment-author {
        margin: 10px 0px;
    }
</style>


<div class="container-fluid mt-2">
        <div class="form-group row">
            <form method="post" class="comment-form" action=".">
                {% csrf_token %}
                {{ comment_form.as_p }}
                {% if request.user.is_authenticated %}
                    <input type="submit" value="댓글 쓰기" class="btn btn-outline-success">
                {% else %}
                    <input type="submit" value="댓글 쓰기" class="btn btn-outline-success" disabled>
                {% endif %}
            </form>
        </div>
    </div>
    <div style="font-size: 25px; font-weight: bold; margin-bottom: 10px;">{{ comments.count }}개의 댓글</div>

<div id="comment-container">
    {% for comment in comments %}
    <blockquote id="comment" class="blockquote">
{#        <span><small>{{ comment.updated_at}}</small></span><span style="margin-left: 10px; color: red;"><small>추천: {{ comment.likes.count }}</small></span>#}

{#        <span><small>{{ comment.updated_at}}</small></span><span style="margin-left: 10px; color: red;"><small>추천: {{ comment.comment_total_likes }}</small></span>#}
        <span id="comment-time"><small>{{ comment.updated_at}}</small></span>

        <div id="comment-author"><strong>{{ comment.author.nickname}}</strong></div>
        <p>{{ comment.message }}</p>
        {% if comment.author == request.user %}
            <a href="{{ comment.get_edit_url }}">
                수정
            </a>
            <a href="{{ comment.get_delete_url }}" class="text-danger">
                삭제
            </a>
        {% endif %}
        <button type="button" name="button" class="reply-btn btn btn-outline-dark btn-sm ml-2">대댓글</button>

        {% if request.user.is_authenticated %}
            <form action="{% url 'main:like_comment' %}" method="post">
                {% csrf_token %}

{#                {% if comment in user.comment_likes.all %}#}
{#                    <button type="submit" name="comment_id" value="{{ comment.id }}" class="btn btn-primary">추천 취소</button>#}
{#                {% else %}#}
{#                    <button type="submit" name="comment_id" value="{{ comment.id }}" class="btn btn-primary">추천</button>#}
{#                {% endif %}#}
				<div class="comment-like" id="comment_like_section{{ comment.id }}">
					{% include 'main/like_comment.html' %}
				</div>
            </form>
        {% endif %}

    </blockquote>

    <div class="replied-comments container mt-2" style="display:none;">
        {% for reply in comment.replies.all %}
        <blockquote class="blockquote">
            <div>{{ reply.updated_at}}</div>
            <div><strong>{{ reply.author.nickname}}</strong></div>
            <p>{{ reply.message }}</p>
            {% if reply.author == request.user %}
                <a href="{{ reply.get_edit_url }}">
                    수정
                </a>
                <a href="{{ reply.get_delete_url }}" class="text-danger">
                    삭제
                </a>
            {% endif %}
        </blockquote>
        {% endfor %}
        <div class="form-group row">
             <form method="post" class="reply-form" action=".">
                 {% csrf_token %}
                <input type="hidden" name="comment_id" value="{{ comment.id }}">
                 {{ comment_form.as_p }}
                 {% if request.user.is_authenticated %}
                     <input type="submit" value="Submit" class="btn btn-outline-success">
                 {% else %}
                    <input type="submit" value="Submit" class="btn btn-outline-success" disabled>
                 {% endif %}
             </form>
        </div>
    </div>
    {% endfor %}
</div>

main/templates/main/detail.html
{% extends 'base.html' %}

{% block content %}
{% load static %}

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

    <style>
        p {
            margin: 3px;
        }

        .entity {
            @import url(//fonts.googleapis.com/earlyaccess/jejugothic.css);
            font-family: 'Jeju Gothic', sans-serif;
        }
        .button_container{
            margin-top: 50px;
            text-align: right;
            margin-right: 200px;
        }

        .content_container{
            margin-left: auto;
            margin-right:auto;
            border: 3px solid grey;
            width: 1300px;
            margin-top: 150px;
            padding: 50px 100px;
        }

    .main_button_container{
        text-align: center;
        margin-bottom: 50px;
    }
    #recommend_star{
        height: 16px;
    }

    i {
        font-size: 60px;
    }

    #scrap-section {
        text-align: center;
    }

    .fas fa-star {
        height: 100px;
    }

    .far fa-star {
        height: 100px;
    }

    textarea {
        overflow: visible;

    }


    </style>

<div class="entity">
    <div class="content_container">
        <div class="row">
             <div class="col-lg-8">
                <h1 class="mt-4">{{ post.title }}</h1>
                <p class="lead">

                                by {{ post.author.nickname }}</p>
            </div>
        </div>
            <hr>
        <div class="row">
            <div class="col-lg-8">
                <p>{{ post.updated_at }}</p>
            </div>
        </div>
            <hr>
        <div class="row">
            <div class="col-lg-8">
                <p style="flex-basis: 400px;">시급: {{ post.payment }}</p>
                <p>지점: {{ post.reside }}</p>
                <p>직종: {{ post.work_type }}</p>
                <p>별점: <img id=recommend_star src="{% static 'main/star.jpg' %}">{{ post.recommend }}</p>
            </div>
        </div>
            <hr>
        <textarea readonly rows="15" cols="110">{{ post.content }}</textarea>
    </div>
    {% if request.user == post.author %}
        <div class="button_container">
            <a href="{% url 'main:edit' post.pk %}" class="btn btn-warning btn btn-primary btn-lg">게시글 수정</a>
            <a href="{% url 'main:delete' post.pk %}" class="btn btn-danger btn btn-primary btn-lg">게시글 삭제</a>
        </div>
    {% endif %}
</div>

<div id="like-section">
    {% include 'main/like_section.html' %}
</div>

<div id="scrap-section">
    {% include 'main/scrap.html' %}
    <script>
        $(document).on('click', '#scrap', function(event){
                event.preventDefault();
                $.ajax({
                type: 'GET',
                url: "{% url 'main:scrap_post' post.id %}",
                success: function(response){
                    $('#scrap-section').html(response['form'])
                },
                error: function(rs, e){
                    console.log(rs.responseText);
                },
            });
        });
    </script>
{#    <p><b>스크랩<b></b></p>#}
{#{% if is_scrap %}#}
{#    <a href="{% url 'main:scrap_post' post.id %}">#}
{#    <i class="fas fa-star"></i>#}
{#    </a>#}
{#{% else %}#}
{#    <a href="{% url 'main:scrap_post' post.id %}">#}
{#    <i class="far fa-star"></i>#}
{#    </a>#}
{#{% endif %}#}
</div>

<div class="main-comment-section" style="margin-left: 5%;">
    {% include 'main/comments.html' %}

</div>
<div class="main_button_container">
    <a href="{%  url 'main:post' %}" class="btn btn-dark btn-lg">더 많은 잡썰보기</a>
    <a href="{% url "main:main" %}" class="btn btn-dark btn-lg">메인으로 돌아가기</a>
</div>
{% endblock %}

main/templates/main/like_comment.html
<body>
{#<small>추천: {{ comment.comment_total_likes }}</small>#}
<span style="color: darkblue; margin-right: 10px;"><bold><i style="font-size:20px; margin-right: 5px;" class="far fa-thumbs-up"></i>추천 수: {{ comment.comment_total_likes }}</bold></span>
{% if comment in user.comment_likes.all %}

	<button type="submit"  name="comment_id" value="{{ comment.id }}" class="btn btn-warning comment_like">추천 취소</button>

{#    <a name="comment_id" value="{{ comment.id }}" href="{% url 'main:like_comment' %}">#}
{#    <i class="far fa-thumbs-up"></i>#}

{% else %}

	<button type="submit" name="comment_id" value="{{ comment.id }}" class="btn btn-primary comment_like">추천</button>
{#    <a name="comment_id" value="{{ comment.id }}" href="{% url 'main:like_comment' %}">#}
{#    <i class="fas fa-thumbs-up"></i>#}

{% endif %}

</body>

main/templates/main/like_section.html
<p style="text-align: center; margin-top: 10%; font-weight: bold;">{{ post.total_likes }}명이 이 글을 추천했어요</p>
    {% if request.user.is_authenticated %}
     <form action="{% url 'main:like_post' %}" method="post">
         {% csrf_token %}
         {% if is_liked %}
         <button type="submit" id='like' name="post_id" value="{{ post.id }}" class="btn btn-primary" style="margin-left:auto;margin-right:auto;display:block;margin-bottom:5%">추천을 취소할래요!</button>
         {% else %}
         <button type="submit" id="like" name="post_id" value="{{ post.id }}" class="btn btn-primary" style="margin-left:auto;margin-right:auto;display:block;margin-bottom:5%">이 게시글을 추천할래요!</button>
         {% endif %}
     </form>
    {% endif %}

main/templates/main/scrap.html
    <p><b>스크랩</b></p>
{% if is_scrap %}
    <a id="scrap" value="{{ post.id }}" href="{% url 'main:scrap_post' post.id %}">
    <i class="fas fa-star"></i>
    </a>
{% else %}
    <a id="scrap" value="{{ post.id }}" href="{% url 'main:scrap_post' post.id %}">
    <i class="far fa-star"></i>
    </a>
{% endif %}